version: '3.8'
services:
  db:
    image: postgres:14
    container_name: db_container
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 5
    restart: on-failure
    volumes:
      - postgresql_volume_compose:/var/lib/postgresql/data
      - ./etl/etl/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    expose:
      - 5432

  movies_admin:
    build:
      context: ./movies_admin/movies_admin
    image: movies-admin-image
    env_file:
      - ./.env
    volumes:
      - static_volume:/home/app/movies_admin/staticfiles
      - media_volume:/home/app/movies_admin/mediafiles
    depends_on:
      db:
        condition: service_healthy
    container_name: movies_admin_container
    restart: unless-stopped
    expose:
      - 8000


  nginx:
    image: nginx:1.22.1
    container_name: nginx_container
    volumes:
      - static_volume:/home/app/movies_admin/staticfiles
      - media_volume:/home/app/movies_admin/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - movies_admin
    restart: always

  redis:
    image: redis:7.0.7
    container_name: redis_container
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - redis_volume:/data
    expose:
      - 6379

  elastic:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - USE_SSL=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9200 | grep -q 'HTTP/1.1 200 OK'",
        ]
      interval: 1s
      timeout: 5s
      retries: 120
    container_name: elastic_compose
    expose:
      - 9200
    volumes:
      - elastic_volume_compose:/usr/share/elasticsearch/data

  etl:
    build:
      context: ./etl/etl
    image: etl-image
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_healthy
      elastic:
        condition: service_healthy
    container_name: etl_container
    restart: unless-stopped

  fastapi:
    build:
      context: ./fastapi
    image: fastapi-image
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elastic:
        condition: service_healthy
    container_name: fastapi_container
    restart: unless-stopped
    expose:
      - 8001

  tests:
    image: fastapi-image
    depends_on:
      - fastapi
    env_file:
      - ./.env
    volumes:
      - ./tests:/tests
      - ./tests/functional/.env.docker:/tests/functional/.env
    entrypoint: >
      sh -c "pip install -r /tests/functional/requirements.txt
      && python3 /tests/functional/utils/wait_for_es.py
      && python3 /tests/functional/utils/wait_for_redis.py
      && python3 -m pytest /tests/functional/src"

volumes:
  static_volume:
  media_volume:
  postgresql_volume_compose:
  redis_volume:
  elastic_volume_compose:
  kibana_volume_compose:
